"""
API Constants.

Standardized HTTP status codes and other API constants.
"""

# HTTP Status Codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_ACCEPTED = 202
HTTP_NO_CONTENT = 204

HTTP_BAD_REQUEST = 400
HTTP_UNAUTHORIZED = 401
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_METHOD_NOT_ALLOWED = 405
HTTP_REQUEST_TIMEOUT = 408
HTTP_CONFLICT = 409
HTTP_GONE = 410
HTTP_TOO_MANY_REQUESTS = 429

HTTP_INTERNAL_ERROR = 500
HTTP_NOT_IMPLEMENTED = 501
HTTP_BAD_GATEWAY = 502
HTTP_SERVICE_UNAVAILABLE = 503
HTTP_GATEWAY_TIMEOUT = 504

# Common API Error Messages
ERROR_INVALID_INPUT = "Invalid input provided"
ERROR_MISSING_REQUIRED_FIELD = "Missing required field"
ERROR_RESOURCE_NOT_FOUND = "Requested resource not found"
ERROR_PERMISSION_DENIED = "Permission denied"
ERROR_RATE_LIMIT_EXCEEDED = "Rate limit exceeded"
ERROR_INTERNAL_SERVER_ERROR = "Internal server error occurred"
