"""NEW: APIRequest and Webhook tables

Revision ID: 15b0123df378
Revises: 6ca9eeae7aa3
Create Date: 2025-12-18 17:15:36.036901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15b0123df378'
down_revision: Union[str, Sequence[str], None] = '6ca9eeae7aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_time_ms', sa.Float(), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('api_version', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='API request logs for analytics and monitoring'
    )
    op.create_index('idx_api_request_active', 'api_requests', ['is_deleted'], unique=False)
    op.create_index('idx_api_request_created', 'api_requests', ['created_at'], unique=False)
    op.create_index('idx_api_request_endpoint_status', 'api_requests', ['endpoint', 'status_code'], unique=False)
    op.create_index(op.f('ix_api_requests_created_at'), 'api_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_requests_endpoint'), 'api_requests', ['endpoint'], unique=False)
    op.create_index(op.f('ix_api_requests_ip_address'), 'api_requests', ['ip_address'], unique=False)
    op.create_index(op.f('ix_api_requests_is_deleted'), 'api_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_api_requests_request_id'), 'api_requests', ['request_id'], unique=True)
    op.create_index(op.f('ix_api_requests_status_code'), 'api_requests', ['status_code'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', sa.Text(), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='Webhook configurations for external notifications'
    )
    op.create_index('idx_webhook_active', 'webhooks', ['is_active', 'is_deleted'], unique=False)
    op.create_index(op.f('ix_webhooks_is_active'), 'webhooks', ['is_active'], unique=False)
    op.create_index(op.f('ix_webhooks_is_deleted'), 'webhooks', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhooks_is_deleted'), table_name='webhooks')
    op.drop_index(op.f('ix_webhooks_is_active'), table_name='webhooks')
    op.drop_index('idx_webhook_active', table_name='webhooks')
    op.drop_table('webhooks')
    op.drop_index(op.f('ix_api_requests_status_code'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_request_id'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_is_deleted'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_ip_address'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_endpoint'), table_name='api_requests')
    op.drop_index(op.f('ix_api_requests_created_at'), table_name='api_requests')
    op.drop_index('idx_api_request_endpoint_status', table_name='api_requests')
    op.drop_index('idx_api_request_created', table_name='api_requests')
    op.drop_index('idx_api_request_active', table_name='api_requests')
    op.drop_table('api_requests')
    # ### end Alembic commands ###
