"""Floodingnaque

Revision ID: 6ca9eeae7aa3
Revises: 
Create Date: 2025-12-18 17:07:41.595347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ca9eeae7aa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_history', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('alert_history', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_alert_active', 'alert_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_alert_history_is_deleted'), 'alert_history', ['is_deleted'], unique=False)
    op.add_column('predictions', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('predictions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_prediction_active', 'predictions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_predictions_is_deleted'), 'predictions', ['is_deleted'], unique=False)
    op.add_column('weather_data', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('weather_data', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('idx_weather_active', 'weather_data', ['is_deleted'], unique=False)
    op.create_index('idx_weather_location_time', 'weather_data', ['location_lat', 'location_lon', 'timestamp'], unique=False)
    op.create_index(op.f('ix_weather_data_is_deleted'), 'weather_data', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_data_is_deleted'), table_name='weather_data')
    op.drop_index('idx_weather_location_time', table_name='weather_data')
    op.drop_index('idx_weather_active', table_name='weather_data')
    op.drop_column('weather_data', 'deleted_at')
    op.drop_column('weather_data', 'is_deleted')
    op.drop_index(op.f('ix_predictions_is_deleted'), table_name='predictions')
    op.drop_index('idx_prediction_active', table_name='predictions')
    op.drop_column('predictions', 'deleted_at')
    op.drop_column('predictions', 'is_deleted')
    op.drop_index(op.f('ix_alert_history_is_deleted'), table_name='alert_history')
    op.drop_index('idx_alert_active', table_name='alert_history')
    op.drop_column('alert_history', 'deleted_at')
    op.drop_column('alert_history', 'is_deleted')
    # ### end Alembic commands ###
