#!/bin/sh
# =====================================================
# FLOODINGNAQUE - PgBouncer Entrypoint Script
# =====================================================
# Configures PgBouncer with environment variables
# =====================================================

set -e

# =====================================================
# Default Configuration Values
# =====================================================
: "${DB_HOST:=localhost}"
: "${DB_PORT:=5432}"
: "${DB_NAME:=floodingnaque}"
: "${DB_USER:=postgres}"
: "${DB_PASSWORD:=password}"
: "${DB_SSL_MODE:=require}"

# Read replica defaults (fallback to primary)
: "${DB_REPLICA_HOST:=$DB_HOST}"
: "${DB_REPLICA_PORT:=$DB_PORT}"

# PgBouncer settings
: "${PGBOUNCER_POOL_MODE:=transaction}"
: "${PGBOUNCER_MAX_CLIENT_CONN:=1000}"
: "${PGBOUNCER_DEFAULT_POOL_SIZE:=25}"
: "${PGBOUNCER_MIN_POOL_SIZE:=5}"
: "${PGBOUNCER_RESERVE_POOL_SIZE:=10}"
: "${PGBOUNCER_MAX_DB_CONNECTIONS:=50}"

# Admin users
: "${PGBOUNCER_ADMIN_USER:=pgbouncer_admin}"
: "${PGBOUNCER_ADMIN_PASSWORD:=admin_password_change_me}"
: "${PGBOUNCER_STATS_USER:=pgbouncer_stats}"
: "${PGBOUNCER_STATS_PASSWORD:=stats_password_change_me}"

echo "========================================"
echo "Floodingnaque PgBouncer Initialization"
echo "========================================"
echo "Primary DB: ${DB_HOST}:${DB_PORT}/${DB_NAME}"
echo "Replica DB: ${DB_REPLICA_HOST}:${DB_REPLICA_PORT}/${DB_NAME}"
echo "Pool Mode: ${PGBOUNCER_POOL_MODE}"
echo "Max Client Connections: ${PGBOUNCER_MAX_CLIENT_CONN}"
echo "Default Pool Size: ${PGBOUNCER_DEFAULT_POOL_SIZE}"
echo "========================================"

# =====================================================
# Generate pgbouncer.ini from template
# =====================================================
echo "Generating pgbouncer.ini configuration..."

# Export all variables for envsubst
export DB_HOST DB_PORT DB_NAME DB_USER DB_PASSWORD DB_SSL_MODE
export DB_REPLICA_HOST DB_REPLICA_PORT
export PGBOUNCER_POOL_MODE PGBOUNCER_MAX_CLIENT_CONN PGBOUNCER_DEFAULT_POOL_SIZE
export PGBOUNCER_MIN_POOL_SIZE PGBOUNCER_RESERVE_POOL_SIZE PGBOUNCER_MAX_DB_CONNECTIONS

# Substitute environment variables in the template
envsubst < /etc/pgbouncer/pgbouncer.ini.template > /etc/pgbouncer/pgbouncer.ini

# =====================================================
# Generate userlist.txt for authentication
# =====================================================
echo "Generating user authentication file..."

# Create userlist.txt with SCRAM-SHA-256 or MD5 hashed passwords
# Format: "username" "password_hash"
cat > /etc/pgbouncer/userlist.txt << EOF
# =====================================================
# PgBouncer User Authentication File
# Generated by entrypoint.sh
# =====================================================

# Database user
"${DB_USER}" "${DB_PASSWORD}"

# Admin user for PgBouncer console
"${PGBOUNCER_ADMIN_USER}" "${PGBOUNCER_ADMIN_PASSWORD}"

# Stats user for monitoring
"${PGBOUNCER_STATS_USER}" "${PGBOUNCER_STATS_PASSWORD}"
EOF

# Set secure permissions
chmod 600 /etc/pgbouncer/userlist.txt

# =====================================================
# Update pgbouncer.ini with dynamic pool settings
# =====================================================
# Override template values with environment-specific settings
sed -i "s/pool_mode = .*/pool_mode = ${PGBOUNCER_POOL_MODE}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/max_client_conn = .*/max_client_conn = ${PGBOUNCER_MAX_CLIENT_CONN}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/default_pool_size = .*/default_pool_size = ${PGBOUNCER_DEFAULT_POOL_SIZE}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/min_pool_size = .*/min_pool_size = ${PGBOUNCER_MIN_POOL_SIZE}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/reserve_pool_size = .*/reserve_pool_size = ${PGBOUNCER_RESERVE_POOL_SIZE}/" /etc/pgbouncer/pgbouncer.ini
sed -i "s/max_db_connections = .*/max_db_connections = ${PGBOUNCER_MAX_DB_CONNECTIONS}/" /etc/pgbouncer/pgbouncer.ini

# =====================================================
# Validate configuration
# =====================================================
echo "Validating PgBouncer configuration..."

if [ ! -f /etc/pgbouncer/pgbouncer.ini ]; then
    echo "ERROR: pgbouncer.ini not found!"
    exit 1
fi

if [ ! -f /etc/pgbouncer/userlist.txt ]; then
    echo "ERROR: userlist.txt not found!"
    exit 1
fi

echo "Configuration files validated successfully."

# =====================================================
# Start PgBouncer
# =====================================================
echo "Starting PgBouncer..."
echo "========================================"

# Execute the command passed to the container
exec "$@"
